baseURL:        "https://hugo-boilerplate.netlify.com/"
languageCode:   "en-us"
title:          "Hugo Boilerplate"
config:         "config.yml"
metaDataFormat: "yaml"
params:
  color: "#000000"
  description: An opinionated base template for Hugo Static Sites Generator
  author:
    name: Imam Susanto
    facebook: https://www.facebook.com/imsus
    email: abc.imams@gmail.com
blackfriday:
  angledQuotes: true
  fractions: false
  plainIDAnchors: true
  extensions:
    - hardLineBreak
    - titleblock
outputFormats:
  instant:
    name: "instant"
    mediaType: "application/rss"
    path: "instant"
    isPlainText: false
    isHTML: false
    noUgly: true
    notAlternative: false
outputs:
  home: 
    - instant
    - html
menu:
  internal:
    - Name: "Single Page"
      Weight: 1
      Identifier: "single"
      URL: "/page/sample/"
    - Name: "List Page (Section)"
      Weight: 2
      Identifier: "list"
      URL: "/page/"
    - Name: "List Page (Taxonomy)"
      Weight: 3
      Identifier: "taxonomy"
      URL: "/categories/uncategorized/"
    - Name: "List Page (Taxonomy Terms)"
      Weight: 4
      Identifier: "terms"
      URL: "/categories/"
  external:
    - Name: "Single AMP"
      Weight: 1
      Identifier: "amp"
      URL: "/amp/page/sample/"
    - Name: "Single JSON"
      Weight: 2
      Identifier: "json-single"
      URL: "/page/sample/index.json"
    - Name: "List JSON"
      Weight: 3
      Identifier: "json-list"
      URL: "/page/index.json"

